# Generated by Django 4.0.3 on 2022-04-10 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50, verbose_name='')),
                ('category_image', models.ImageField(upload_to='./media/images/', verbose_name='')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_name', models.CharField(max_length=50, verbose_name='')),
                ('channel_image', models.ImageField(upload_to='./media/images/', verbose_name='')),
            ],
            options={
                'verbose_name': 'Channel',
                'verbose_name_plural': 'Channels',
            },
        ),
        migrations.CreateModel(
            name='Star',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('star_name', models.CharField(max_length=50, verbose_name='')),
                ('star_image', models.ImageField(upload_to='./media/images/', verbose_name='')),
                ('star_dob', models.CharField(max_length=50, verbose_name='')),
                ('star_bio', models.TextField(verbose_name='')),
                ('star_boob_size', models.CharField(max_length=50, verbose_name='')),
                ('star_gender', models.CharField(choices=[('Female', 'Female'), ('Male', 'Male'), ('Trans', 'Trans')], default='Female', max_length=50, verbose_name='')),
            ],
            options={
                'verbose_name': 'Star',
                'verbose_name_plural': 'Stars',
            },
        ),
        migrations.CreateModel(
            name='Staralias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('star_alias_name', models.CharField(max_length=50, verbose_name='')),
            ],
            options={
                'verbose_name': 'Staralias',
                'verbose_name_plural': 'Staraliass',
            },
        ),
        migrations.CreateModel(
            name='Subsite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subsite_name', models.CharField(max_length=50, verbose_name='')),
                ('subsite_image', models.ImageField(upload_to='./media/images/', verbose_name='')),
            ],
            options={
                'verbose_name': 'subsite',
                'verbose_name_plural': 'subsites',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=50, verbose_name='')),
                ('tag_image', models.ImageField(upload_to='./media/images/', verbose_name='')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_name', models.CharField(max_length=50, verbose_name='')),
                ('video_image', models.ImageField(upload_to='./media/images/', verbose_name='')),
                ('video_pub_date', models.DateField(verbose_name='')),
                ('video_path', models.CharField(max_length=50, verbose_name='')),
                ('video_category', models.ManyToManyField(to='videos.category', verbose_name='')),
                ('video_channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videos.channel', verbose_name='')),
                ('video_stars', models.ManyToManyField(to='videos.star', verbose_name='')),
                ('video_tags', models.ManyToManyField(to='videos.tag', verbose_name='')),
            ],
            options={
                'verbose_name': 'Video',
                'verbose_name_plural': 'Videos',
            },
        ),
        migrations.AddField(
            model_name='star',
            name='star_alias',
            field=models.ManyToManyField(to='videos.staralias', verbose_name=''),
        ),
        migrations.AddField(
            model_name='channel',
            name='channel_subsite',
            field=models.ManyToManyField(to='videos.subsite', verbose_name=''),
        ),
    ]
