# Generated by Django 4.0.3 on 2022-04-10 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_channel_channel_url_subsite_subsite_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='channel_subsite',
            field=models.ManyToManyField(to='videos.subsite', verbose_name='Subsites'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_pub_date',
            field=models.DateField(blank=True, verbose_name='Video Published'),
        ),
    ]
