# Generated by Django 4.0.3 on 2022-04-10 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0004_alter_video_video_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_channel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='videos.channel', verbose_name='Channel'),
        ),
    ]
